export const CART_ITEMS = 'cart/CART_ITEMS'
export const CART_COUNT = 'cart/CART_COUNT'
export const CART_CHANGE = 'cart/CART_CHANGE'
export const CART_INCLUDE = 'cart/CART_INCLUDE'
export const CART_EXCLUDE = 'cart/CART_EXCLUDE'
export const CART_CHANGE_QUANTITY = 'cart/CART_CHANGE_QUANTITY'

export const BOOTS = 'boots/BOOTS'
export const BOOTS_RELEASES = 'boots/BOOTS_RELEASES'
export const BOOTS_BEST_SELLERS = 'boots/BOOTS_BEST_SELLERS'
export const BOOTS_CHANGE = 'boots/BOOTS_CHANGE'
export const BOOTS_LOAD = 'boots/BOOTS_LOAD'
